"""File templates for `mt ship` scaffolds — plain strings, no template engine."""

from __future__ import annotations

from importlib import metadata

SERVE_PY = '''\
"""Generated by `mt ship` — serves the exported model in ./model.

Run locally:  uv run --with-requirements requirements.txt uvicorn serve:app --port 8000
(or, with the requirements installed: uvicorn serve:app --host 0.0.0.0 --port 8000)
"""

from pathlib import Path
from typing import Any

import mlflow.pyfunc
import numpy as np

from mlops_toolbox.core.models import ModelContract
from mlops_toolbox.factories import model_server

_HERE = Path(__file__).parent


class _PyfuncAdapter:
    framework = "mlflow_pyfunc"

    def __init__(self, model: Any) -> None:
        self._model = model

    def predict(self, X: Any) -> np.ndarray:
        return np.asarray(self._model.predict(X))

    def predict_proba(self, X: Any) -> None:
        return None


def build_app() -> Any:
    model = _PyfuncAdapter(mlflow.pyfunc.load_model(str(_HERE / "model")))
    contract_path = _HERE / "contract.json"
    contract = (
        ModelContract.model_validate_json(contract_path.read_text(encoding="utf-8"))
        if contract_path.exists()
        else None
    )
    return model_server().build_app(model, contract=contract)


app = build_app()

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
'''

DOCKERFILE = """\
FROM python:3.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY requirements.txt .
RUN uv pip install --system --no-cache -r requirements.txt
COPY . .

EXPOSE 8000
CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8000"]
"""


def requirements_txt() -> str:
    """Pin the serving dependencies to the versions installed right now."""
    lines = ["mlops-toolbox[deploy,registry]"]
    for package in ("mlflow", "fastapi", "uvicorn", "numpy", "pandas"):
        try:
            lines.append(f"{package}=={metadata.version(package)}")
        except metadata.PackageNotFoundError:
            lines.append(package)
    return "\n".join(lines) + "\n"


# --- `mt init` project scaffold -------------------------------------------------
# Templates use the {{project}} placeholder, replaced at scaffold time so the
# generated files can freely contain f-strings and YAML braces.

INIT_TRAIN_PY = '''\
"""Training entry point for {{project}} — generated by `mt init`.

Trains, evaluates, and registers the model with its contract (input schema,
evaluation report, drift baseline), so serving, scoring, monitoring, and CI
gates all work downstream with no extra configuration.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

import mlops_toolbox as mt

# Resolved from mlops.toml / MT_TRACKING_URI, falling back to the local default —
# point the whole project at a shared MLflow server by editing mlops.toml only.
TRACKING_URI = mt.load_settings().tracking_uri
MODEL_NAME = "{{project}}"


def load_data() -> tuple[pd.DataFrame, pd.Series]:
    # TODO: replace with your real data loading.
    rng = np.random.default_rng(42)
    n = 500
    X = pd.DataFrame(
        {
            "feature_a": rng.normal(size=n),
            "feature_b": rng.normal(size=n),
        }
    )
    y = pd.Series((X["feature_a"] + 0.5 * X["feature_b"] > 0).astype(int), name="target")
    return X, y


def train(X_train: pd.DataFrame, y_train: pd.Series):
    # TODO: replace with your real model.
    from sklearn.linear_model import LogisticRegression

    return LogisticRegression().fit(X_train, y_train)


def main() -> None:
    X, y = load_data()
    split = mt.train_test_split(X, y, test_size=0.2, random_state=42)

    model = mt.adapt(train(split.X_train, split.y_train))

    tracker = mt.tracker(tracking_uri=TRACKING_URI, experiment_name=MODEL_NAME)
    tracker.start_run()
    report = mt.ClassificationEvaluator().evaluate(split.y_test, model.predict(split.X_test))
    tracker.log_metrics(report.metrics)
    run = tracker.end_run()

    registry = mt.model_registry(TRACKING_URI)
    info = registry.register_model(
        model,
        name=MODEL_NAME,
        run_id=run.run_id,
        contract=mt.infer_contract(split.X_train, y=split.y_train, evaluation=report),
        reference_data=split.X_train,
    )
    registry.set_alias(MODEL_NAME, info.version, "production")
    mt.register_project(MODEL_NAME, TRACKING_URI)
    print(f"Registered {MODEL_NAME} v{info.version} (alias 'production')")


if __name__ == "__main__":
    main()
'''

INIT_CI_WORKFLOW = """\
name: model-ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  train-and-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Train and register
        run: python train.py
      - name: Quality gate
        # TODO: tighten the thresholds for your model.
        # The tracking URI resolves from mlops.toml (checked in with the project).
        run: mt gate "accuracy>=0.8" --model {{project}}
      - name: Lifecycle audit
        run: mt doctor
"""

INIT_MLOPS_TOML = """\
# mlops-toolbox settings for {{project}}.
# Resolution order: CLI flags > MT_* environment variables > this file > defaults.
# Check this file in. Never put secrets here — cloud credentials come from your
# provider's default chain, API keys from environment variables.

tracking_uri = "sqlite:///mlops.db"

# Team-shared setup: point at a remote MLflow server instead, e.g.
# tracking_uri = "https://mlflow.internal.example.com"
# registry_uri = "https://mlflow.internal.example.com"   # only if different from tracking

# [aws]
# region = "eu-west-1"
# execution_role_arn = "arn:aws:iam::123456789012:role/sagemaker-execution"
# artifact_bucket = "my-ml-artifacts"
# ecr_repository = "my-models"

# [gcp]
# project = "my-gcp-project"
# region = "europe-west1"
# staging_bucket = "my-ml-staging"
# artifact_registry_repo = "my-models"

# [azure]
# subscription_id = "00000000-0000-0000-0000-000000000000"
# resource_group = "ml-rg"
# workspace_name = "ml-workspace"
# acr_name = "mymodelsacr"
"""

INIT_REQUIREMENTS = """\
mlops-toolbox[all]
scikit-learn
"""

INIT_GITIGNORE = """\
mlops.db
mlruns/
mlartifacts/
__pycache__/
deploy/
"""

INIT_README = """\
# {{project}}

Generated by `mt init`. The full lifecycle in four commands:

```bash
pip install -r requirements.txt
python train.py                       # train, evaluate, register with contract
mt doctor {{project}}                 # audit lifecycle completeness
mt serve {{project}} --version production   # typed /predict from the contract
```

Also available once trained: `mt score` (batch scoring), `mt drift` (baseline
drift checks), `mt gate` (CI quality gates, wired into
`.github/workflows/model-ci.yml`), `mt card` (model card), `mt ship`
(self-contained deployable folder).
"""


def render_init_file(template: str, project: str) -> str:
    return template.replace("{{project}}", project)


def readme_md(name: str, version: str, has_contract: bool) -> str:
    predict_example = (
        'curl -X POST http://localhost:8000/predict \\\n'
        '  -H "Content-Type: application/json" \\\n'
        "  -d '{\"records\": [{...one object per input column...}]}'\n\n"
        "GET /contract describes the expected columns and types."
        if has_contract
        else 'curl -X POST http://localhost:8000/predict \\\n'
        '  -H "Content-Type: application/json" \\\n'
        "  -d '{\"instances\": [[1.0, 2.0]]}'"
    )
    return f"""\
# {name} (v{version}) — generated by `mt ship`

Self-contained model service: the model artifacts live in `./model`, no
tracking server needed.

## Run locally

With [uv](https://docs.astral.sh/uv/) — no environment setup needed:

```bash
uv run --with-requirements requirements.txt uvicorn serve:app --host 0.0.0.0 --port 8000
```

Or with pip:

```bash
pip install -r requirements.txt
uvicorn serve:app --host 0.0.0.0 --port 8000
```

## Run with Docker

```bash
docker build -t {name}-service .
docker run -p 8000:8000 {name}-service
```

## Predict

```bash
{predict_example}
```
"""
